language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: rN5qRutxMojMWAK57i8cC5E3AHiBlTMx0WKYlNEN7vMX0Z1GUBOA/BjYypRcagLWaRaADKNm88o0nIQOn/BhQ1rb27pxgBKMLUIuq4QVW2HaidqJ51h802s3rV5fstyGU2lz/r3DgOFHicJHTZlcf8wMU4hFMpvGjw8gWgGx6qR3Z0Jrtp7wvRND3vauc7rcUt+JysS4ZHvQnXFBiDNpTsFY6hW4GZsC/tSGVL10eo+9lsT4VOJKb4bdl2cXgfmflpwCdLjGjodmiivXha1/ztQyi86tld/eRrikZmVjQTNr77lhmLNTzs5QR19XWmhpje0U65xf08Hwjf6wF/3LnUbPbQGemALGHmJRy030PlG4keXDvARNFFWEEtaEbZMbHIcn3SeYjDtjN5+y5J1ogTbe8SmppIyZkpKEfhWQT0Yo/envT88FZBirdqhZfDcLOLTx29QJVHZxs3ex8QnIVWPWbbI2NHy58fOfsJxiGbnxgQBa+bPqDLsOvff3DhtjitQowxL9L8RA8goLLZ0RFXYewIqX9SVyjDK4rWNVSX5u3AMhigvdIRymvqMHNwZ04ZPTU9+8SFT50CroVxKOKcUqmqe2m74pxB69LWAl8ApIf6hQm8A1JdP2XOONmJbI0sGhMrfcaFQh2dxbCmZPlUQ3mRvz1QExnxQaKw/sZhw=
  app: node-shopping-list-integration-tests
  on:
    repo: Redrogue12/node-shopping-list-integration-tests
